/**
 * Embeds `content/**\/*.md` into a TypeScript module.
 *
 * Cloudflare Workers has no filesystem: `node:fs` resolves to unenv stubs that
 * throw at runtime. Reading the markdown during the build and emitting it as a
 * plain module keeps the app graph filesystem-free, so pages render correctly
 * even on an incremental-cache miss.
 */
import { mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const OUT_FILE = join(ROOT, "lib/generated/content-files.ts");

function readCollection(name) {
  const dir = join(ROOT, "content", name);
  return readdirSync(dir)
    .filter((file) => file.endsWith(".md"))
    .sort()
    .map((file) => [file.replace(/\.md$/, ""), readFileSync(join(dir, file), "utf-8")]);
}

function serialize(exportName, entries) {
  const body = entries
    .map(([slug, raw]) => `  ${JSON.stringify(slug)}: ${JSON.stringify(raw)},`)
    .join("\n");
  return `export const ${exportName}: Record<string, string> = {\n${body}\n};\n`;
}

const projects = readCollection("projects");
const posts = readCollection("blog");

mkdirSync(dirname(OUT_FILE), { recursive: true });
writeFileSync(
  OUT_FILE,
  [
    "// AUTO-GENERATED by scripts/generate-content.mjs — do not edit.",
    "// Regenerated on every `npm run build` / `npm run dev`.",
    "",
    serialize("projectFiles", projects),
    serialize("postFiles", posts),
  ].join("\n"),
  "utf-8",
);

console.log(
  `generate-content: embedded ${projects.length} projects, ${posts.length} posts -> lib/generated/content-files.ts`,
);
